name: Generate SQL Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install SQLite
      run: sudo apt-get install sqlite3

    - name: Create SQLite database from SQL file
      run: |
        sqlite3 database.db < example.sql
        sqlite3 database.db "SELECT name FROM sqlite_master WHERE type='table';"

    - name: Download SchemaSpy
      run: wget https://github.com/schemaspy/schemaspy/releases/download/v6.2.4/schemaspy-6.2.4.jar

    - name: Download SQLite JDBC Driver
      run: wget https://github.com/xerial/sqlite-jdbc/releases/download/3.43.0.0/sqlite-jdbc-3.43.0.0.jar

    - name: Generate Documentation
      run: |
        java -jar schemaspy-6.2.4.jar -t sqlite -dp sqlite-jdbc-3.43.0.0.jar -db ./database.db -u dummy -o schemaspy-output -debug -sso -cat % -driver org.sqlite.JDBC

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./schemaspy-output
