name: Generate SQL Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install SQLite
      run: sudo apt-get install sqlite3

    - name: Create SQLite database from SQL file
      run: |
        sqlite3 database.db < example.sql
        
    - name: Download SchemaSpy
      run: wget https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar

    - name: Download SQLite JDBC Driver
      run: wget https://github.com/xerial/sqlite-jdbc/releases/download/3.36.0.3/sqlite-jdbc-3.36.0.3.jar

    - name: Generate Documentation
      run: |
        java -jar schemaspy-6.1.0.jar -t sqlite -dp sqlite-jdbc-3.36.0.3.jar -db database.db -o schemaspy-output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./schemaspy-output
